spring:
  datasource:
    username: ${DB_USERNAME}
    url: jdbc:mysql://${DB_HOST}
    password: ${DB_PASSWORD}
server:
  port: '3000'
  error:
    include-message: always
management:
  endpoints:
    enabled-by-default: false
  health:
    enabled: true
  web:
    exposure:
      include: health,info
  beans:
    cache:
      time-to-live: 5s