name: SEP6 Backend
run-name: CI & CD worfklows for the Kubernetes deployment 🚀
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        working-directory: backend
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tomondre/sep6-backend:${{ github.run_number }}
          build-args: |
            DB_HOST=${{ secrets.DB_HOST }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
  CD:
    runs-on: self-hosted
    needs: CI
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      KUBE_CONFIG_PATH: ~/kubeconfig.yaml
      TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_TOKEN }}
    working-directory: backend/infrastructure
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Terraform Initialize
        run: terraform init
      - name: Set-up kube config
        run: echo "${{ secrets.KUBE_CONFIG }}" > ~/kubeconfig.yaml
      - name: Terraform apply
        run: terraform apply -auto-approve -var "image_tag=${{ github.run_number }}"
