name: CI/CD for Backend

on:
  push:
    branches:
      - main
#    paths:
#      - 'backend/**'
  workflow_dispatch:

env:
  ECR_REPOSITORY: sep6-backend
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        working-directory: backend
        run: |
          FULL_REPO_PATH=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker build -t $FULL_REPO_PATH .
          docker push $FULL_REPO_PATH
